const constants ={
    GET_DATA_SUCCESS:"GET_DATA_SUCCESS",
    GET_DATA_LOADING:"GET_DATA_LOADING",
    GET_DATA_FAILED:"GET_DATA_FAILED",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_LOADING:"LOGIN_LOADING",
    LOGIN_FAILED:"LOGIN_FAILED",
    AUTH_SUCCESS:"AUTH_SUCCESS",
    AUTH_LOADING:"AUTH_LOADING",
    AUTH_FAILED:"AUTH_FAILED",
    LOGOUT:"LOGOUT"
}
export default constants